production:
  <<: *default
  database: book_server_production
  username: book_server
  password: <%= ENV["BOOK_SERVER_DATABASE_PASSWORD"] %>


default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: book_server_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: book_server_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>